language: node_js

node_js:
  - 5.2

env:
  - CXX=g++-4.8

addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g firebase-tools
  - npm install

script:
  - ./scripts/dist.sh

after_success:
  - ./scripts/deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change
